language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-11
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
script:
  - sudo unlink /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-11 /usr/bin/gcc
  - sudo unlink /usr/bin/g++
  - sudo ln -s /usr/bin/g++-11 /usr/bin/g++
  - g++ -v
  - ./build.sh && ./build.sh install && ./build.sh test
notifications:
  email: never